### ISSUE TITLE
大家小心病毒

### ISSUE THREAD

**Issue by linjuchen** [cshaptx4869/phpQuery#1]
https://zhuanlan.zhihu.com/p/235043130

**Comment by cshaptx4869** [comment]
![Screenshot_20200915_105708](https://user-images.githubusercontent.com/31907940/93160826-c77dc780-f743-11ea-8673-2910050cbe6e.jpg)
首先造成你的困扰很抱歉 但这个项目一开始也申明了只是官方项目的搬运 如果觉得有问题或者不放心食用还请及时卸载 以免造成不必要的损失
